spring:
    datasource:
#Dev
        url: jdbc:mysql://101.132.160.107:3306/smartchannel?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: Baiyete_8888
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        show-sql: true
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
      
callback: 
  ipAddress: http://localhost

yzf:
  url: http://47.104.220.122:18500
  payKey: ff604dec92344462b985a3ec02c1ad4a
  paySecret: 5cc8fe60d0814a63a79f2eac7a96afc6
  platMerchant: DEV88882019111310001145