spring:
    datasource:
        #url: jdbc:mysql://rm-uf6935n6wvhoo3a4qio.mysql.rds.aliyuncs.com:3306/smartchannel?useUnicode=true&characterEncoding=UTF-8        
        url: jdbc:mysql://101.132.160.107:3306/smartchannel?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        show-sql: true
        minIdle: 20
        maxActive: 200
        initialSize: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
      
callback: 
  #ipAddress: http://47.91.204.60
  #ipAddress: http://47.101.3.251
  ipAddress: 
  #ipAddress: http://106.14.53.54
  #ipAddress: http://106.15.159.189
  
